name: Rust Build

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: build release
        run: ./build/build.sh
      - name: upload binary artifact linux_amd64
        uses: actions/upload-artifact@v4
        with:
          name: neo
          path: target/release/neo

  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: build release
        run: ./build/build.ps1
      - name: upload binary artifact windows_amd64
        uses: actions/upload-artifact@v4
        with:
          name: neo
          path: target/release/neo.exe
