name: Rust Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: build release
        run: ./build/build.sh
      - name: upload binary artifact linux_amd64
        uses: actions/upload-artifact@v4
        with:
          name: neo
          path: target/release/neo
      - name: upload binary artifact windows_amd64
        uses: actions/upload-artifact@v4
        with:
          name: neo.exe
          path: target/x86_64-pc-windows-gnu/release/neo.exe
